### ISSUE TITLE
A sim has an absolute time counter

### ISSUE THREAD

**Issue by swom** [swom/Timo-s-and-Stefano-s-project#20]
A member that keeps track of the total number of timesteps
This test has to pass, find it in simulation.cpp:

```c++
#ifdef FIX_ISSUE_20
  //A simulation has an absolute counter and you can access it
  {
    simulation s;
    assert(s.get_absolute_time() > 0 | s.get_absolute_time() <= 0);
  }
#endif
```

**Comment by TimoVE9000** [comment]
I did this issue,  but it did suggest to add parentheses arround the test so it became:
I also initialized time at 0 because that made sense eventhough it was not strictly required to pass test

  //A simulation has an absolute counter and you can access it
  {
    simulation s;
    assert((s.get_time() > 0) | (s.get_time() <= 0));
  }

**Comment by swom** [comment]
That's fine, was it not working without the parenthesis?

**Comment by TimoVE9000** [comment]
yes it was, but it gave a warning, and all warnings are treated as errors
