### ISSUE TITLE
Every time tick(simulation) simulation timesteps increase by 1 

### ISSUE THREAD

**Issue by swom** [swom/Timo-s-and-Stefano-s-project#26]
This issue depends on:
- [x] #20 
The following test should pass in simulation.cpp:
```c++
void test_simulation(){

//Other tests

#ifdef FIX_ISSUE_26
  //Every tick simulation timer increases by one
  {
    simulation s;
    auto init_timer_value = s.get_time();
    tick(s);
    assert(s.get_time == init_timer_value + 1);

    simulation s2;
    init_timer_value = s2.get_time();
    int repeats = 123;
    for(int i = 0; i != repeats; i++)
      {
        tick(s);
      }
    assert(s2.get_time() == init_timer_value + repeats);
  }
#endif
}
```

**Comment by TimoVE9000** [comment]
I ended up changing the test a little bit, I think this does the trick as well, but perhaps I am wrong

{
    simulation s;
    auto init_timer_value = s.get_time();
    s.tick();
    assert(s.get_time() == init_timer_value + 1);

    simulation s2;
    init_timer_value = s2.get_time();
    int repeats = 123;
    for(int i = 0; i != repeats; i++)
      {
        s2.tick();
      }
    assert(s2.get_time() == init_timer_value + repeats);
  }
