### ISSUE TITLE
It is possible to check if the environemnt has to change, it should change once every change_probability/1

### ISSUE THREAD

**Issue by swom** [swom/Timo-s-and-Stefano-s-project#34]
The following test should pass in simulation.cpp:
```c++
#ifdef FIX_ISSUE_34
  {
    simulation s;
    int repeats = 10000;
    int n_switches = 0;
    for(int i = 0; i != repeats; i++)
      {
        if(is_environment_changing(s))
          {
            n_switches++;
          }
      }
    assert(n_switches - s.get_change_freq() / repeats < 10 &&
           n_switches - s.get_change_freq() / repeats > -10);
  }
#endif
```

**Comment by TimoVE9000** [comment]
Eeh ok so I assume it should be n_switches - s.get_change_freq() * repeats
So that it checks if the number of observed changes is equal to the number of predicted ones based on the frequency and the nr of repeats

  //#define FIX_ISSUE_34

  {
    simulation s;
    int repeats = 10000;
    int n_switches = 0;
    for(int i = 0; i != repeats; i++)
      {
        if(is_environment_changing(s))
          {
            n_switches++;
          }
      }
    assert(n_switches - s.get_change_freq() * repeats < 10 &&
           n_switches - s.get_change_freq() * repeats > -10);
  }
