### ISSUE TITLE
environment can be initialized by env_param file 

### ISSUE THREAD

**Issue by swom** [swom/Timo-s-and-Stefano-s-project#35]
The following test should pass:
In environment.cpp
```c++
//#define FIX_ISSUE_35
#ifdef  FIX_ISSUE_35
  {
    double targetA = 123456;
    double targetB = 46589;

    env_param e_p{targetA, targetB};
    environment e{e_p};
    assert(are_equal_with_tolerance(e.get_target_valueA(), targetA));
    assert(are_equal_with_tolerance(e.get_target_valueB(), targetB));

  }
#endif
```

**Comment by TimoVE9000** [comment]
Ok, so I changed the test somewhat:
Two things: 
get target value should take an environment as an argument as it is currently written
it seems to be impossible to have a struct output all its member variables, so you have to individually extract them, I think, but I may be wrong/stupid. Alternatively we could maybe initialize environment to only take a struct in its constructor, but I don't how how to do this, plus I think that would break every other test (where A and B are seperately initialized in e).

So then the test would become:
  {
    double targetA = 123456;
    double targetB = 46589;

    env_param e_p{targetA, targetB};
    environment e{e_p.targetA, e_p.targetB};
    assert(are_equal_with_tolerance(get_target_valueA(e), targetA));
    assert(are_equal_with_tolerance(get_target_valueB(e), targetB));

  }
